"""Create files and features

Revision ID: 0001
Revises:
"""

import sqlalchemy as sa
from alembic import op

revision = "0001"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "files",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("filename", sa.String(length=255), nullable=False),
        sa.Column("format", sa.String(length=16), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("crs", sa.Text(), nullable=True),
        sa.Column("crs_wkt", sa.Text(), nullable=True),
        sa.Column("crs_origin", sa.String(length=32), nullable=True),
        sa.Column("layers", sa.JSON(), nullable=False),
        sa.Column("feature_count", sa.Integer(), nullable=False),
        sa.Column("measured_count", sa.Integer(), nullable=False),
        sa.Column("error_count", sa.Integer(), nullable=False),
        sa.Column("not_applicable_count", sa.Integer(), nullable=False),
        sa.Column("unsupported_count", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.String(length=40), nullable=False),
        sa.Column("completed_at", sa.String(length=40), nullable=True),
        sa.Column("processing_ms", sa.Float(), nullable=True),
        sa.Column("warnings", sa.JSON(), nullable=False),
        sa.Column("error", sa.JSON(), nullable=True),
        sa.Column("policy_version", sa.String(length=32), nullable=False),
        sa.CheckConstraint("status IN ('PROCESSING','COMPLETED','COMPLETED_WITH_ERRORS','FAILED')"),
        sa.CheckConstraint(
            "feature_count >= 0 AND measured_count >= 0 AND error_count >= 0 AND "
            "not_applicable_count >= 0 AND unsupported_count >= 0"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "features",
        sa.Column("file_id", sa.String(length=36), nullable=False),
        sa.Column("feature_index", sa.Integer(), nullable=False),
        sa.Column("layer_index", sa.Integer(), nullable=False),
        sa.Column("layer_name", sa.Text(), nullable=False),
        sa.Column("source_feature_id", sa.Text(), nullable=True),
        sa.Column("geometry_type", sa.String(length=64), nullable=True),
        sa.Column("original_wkb", sa.LargeBinary(), nullable=True),
        sa.Column("geometry", sa.JSON(), nullable=True),
        sa.Column("properties", sa.JSON(), nullable=False),
        sa.Column("measurement_status", sa.String(length=32), nullable=False),
        sa.Column("measurement_kind", sa.String(length=16), nullable=True),
        sa.Column("measurement_value", sa.Float(), nullable=True),
        sa.Column("measurement_unit", sa.String(length=8), nullable=True),
        sa.Column("measurement_crs", sa.String(length=32), nullable=True),
        sa.Column("errors", sa.JSON(), nullable=False),
        sa.Column("warnings", sa.JSON(), nullable=False),
        sa.CheckConstraint(
            "(measurement_status = 'MEASURED' AND measurement_value IS NOT NULL AND "
            "measurement_value >= 0 AND measurement_kind IS NOT NULL AND measurement_unit"
            " IS NOT NULL AND measurement_crs IS NOT NULL) OR (measurement_status != "
            "'MEASURED' AND measurement_value IS NULL AND measurement_kind IS NULL AND "
            "measurement_unit IS NULL AND measurement_crs IS NULL)"
        ),
        sa.CheckConstraint(
            "measurement_status IN ('MEASURED','NOT_APPLICABLE','UNSUPPORTED','ERROR')"
        ),
        sa.CheckConstraint("feature_index >= 0 AND layer_index >= 0"),
        sa.ForeignKeyConstraint(["file_id"], ["files.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("file_id", "feature_index"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("features")
    op.drop_table("files")
    # ### end Alembic commands ###
