"""Generate original, redistributable fixtures from mathematically known shapes."""

import json
from pathlib import Path
from tempfile import TemporaryDirectory
from zipfile import ZIP_DEFLATED, ZipFile, ZipInfo

import numpy as np
import shapely
from pyogrio.raw import write
from pyproj import Transformer
from shapely.geometry import LineString, MultiPolygon, Polygon


def square(x=500000, y=2000000, side=100):
    return Polygon([(x, y), (x + side, y), (x + side, y + side), (x, y + side), (x, y)])


def shape_zip(
    target: Path, geometries, crs="EPSG:32643", *, include_prj=True, directory="survey", fields=None
):
    fields = fields or {"name": [f"Feature {i}" for i in range(len(geometries))]}
    with TemporaryDirectory() as temp:
        path = Path(temp) / "survey.shp"
        write(
            path,
            np.array([shapely.to_wkb(g) for g in geometries], dtype=object),
            [np.array(values) for values in fields.values()],
            list(fields),
            driver="ESRI Shapefile",
            geometry_type=geometries[0].geom_type,
            crs=crs,
            encoding="UTF-8",
        )
        with ZipFile(target, "w") as archive:
            for component in sorted(Path(temp).glob("survey.*")):
                if component.suffix == ".prj" and not include_prj:
                    continue
                name = f"{directory}/{component.name}" if directory else component.name
                info = ZipInfo(name, date_time=(2020, 1, 1, 0, 0, 0))
                info.compress_type = ZIP_DEFLATED
                info.external_attr = 0o100644 << 16
                data = component.read_bytes()
                # DBF header contains a creation date; normalize it for reproducibility.
                if component.suffix == ".dbf":
                    data = data[:1] + bytes((120, 1, 1)) + data[4:]
                archive.writestr(info, data)


def build_samples(destination: Path):
    destination.mkdir(parents=True, exist_ok=True)
    parcel = square()
    line = LineString([(500000, 2000000), (500300, 2000400)])
    hole = Polygon(parcel.exterior.coords, [square(500020, 2000020, 20).exterior.coords])
    multi = MultiPolygon([square(), square(500200)])
    shape_zip(
        destination / "projected_polygons.zip",
        [parcel, hole, multi],
        fields={"name": ["Square", "With hole", "Multipart"], "parcel_id": [1, 2, 3]},
    )
    shape_zip(destination / "projected_lines.zip", [line])
    converter = Transformer.from_crs(32643, 4326, always_xy=True)
    geographic = shapely.transform(parcel, converter.transform, interleaved=False)
    shape_zip(destination / "geographic_polygons.zip", [geographic], crs="EPSG:4326")
    shape_zip(destination / "missing_crs.zip", [geographic], crs="EPSG:4326", include_prj=False)
    polygon_coordinates = " ".join(f"{x:.15f},{y:.15f},0" for x, y in geographic.exterior.coords)
    road_coordinates = " ".join(
        f"{x:.15f},{y:.15f},0"
        for x, y in shapely.transform(line, converter.transform, interleaved=False).coords
    )
    x, y = converter.transform(500000, 2000000)
    kml = f"""<?xml version="1.0" encoding="UTF-8"?>
<kml xmlns="http://www.opengis.net/kml/2.2"><Document><name>Local survey</name>
<Folder><name>Parcels</name><Placemark id="parcel-1"><name>Square</name>
<ExtendedData><Data name="parcel_id"><value>1</value></Data></ExtendedData>
<Polygon><outerBoundaryIs><LinearRing><coordinates>{polygon_coordinates}</coordinates></LinearRing></outerBoundaryIs></Polygon>
</Placemark></Folder><Folder><name>Roads and markers</name>
<Placemark id="road-1"><name>Road</name><LineString><coordinates>{road_coordinates}</coordinates>
</LineString></Placemark>
<Placemark id="marker-1"><name>Survey marker</name>
<Point><coordinates>{x:.15f},{y:.15f},12</coordinates>
</Point></Placemark>
</Folder></Document></kml>"""
    (destination / "survey.kml").write_text(kml, encoding="utf-8")
    (destination / "expected.json").write_text(
        json.dumps(
            {
                "provenance": (
                    "Original synthetic fixtures generated by scripts/generate_samples.py"
                ),
                "reference_crs": "EPSG:32643",
                "projected_polygons.zip": [10000, 9600, 20000],
                "projected_lines.zip": [500],
                "geographic_polygons.zip": [10000],
                "survey.kml": {"feature_count": 3, "area_m2": 10000, "length_m": 500},
                "missing_crs.zip": "CRS_REQUIRED without source_crs=EPSG:4326",
            },
            indent=2,
        )
        + "\n"
    )


if __name__ == "__main__":
    build_samples(Path("samples"))
